// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe7s_ebnwfSuYI7Hu4DcyyyTGH4fAI1ZM',
    appId: '1:166240270671:android:36a9493bf75a66719aed3a',
    messagingSenderId: '166240270671',
    projectId: 'emotion-based-music-play-f2106',
    storageBucket: 'emotion-based-music-play-f2106.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX3BsH8tw5cw7srtSJlbxx_fV7UVUQlSE',
    appId: '1:166240270671:ios:e07fefee8001ef679aed3a',
    messagingSenderId: '166240270671',
    projectId: 'emotion-based-music-play-f2106',
    storageBucket: 'emotion-based-music-play-f2106.appspot.com',
    androidClientId:
        '166240270671-hf039n32kut55ku8qq4ahnctmpd18628.apps.googleusercontent.com',
    iosClientId:
        '166240270671-u70kqb8l1el0u5ojqm3ua0epmn72llrm.apps.googleusercontent.com',
    iosBundleId: 'com.example.MusicPlayer',
  );
}
